"""Strategy validation and robustness analysis package."""

from .benchmarks import ValidationBenchmarkResult, ValidationBenchmarkRunner
from .engine import ValidationEngine
from .exceptions import ValidationDataError, ValidationError, ValidationPersistenceError
from .models import (
    BootstrapResult,
    CandidateComparisonReport,
    CandidateValidationProfile,
    CPCVResult,
    CPCVSplit,
    DeflatedSharpeResult,
    MultipleTestingResult,
    ParameterSensitivityResult,
    ParameterSensitivitySnapshot,
    PBOFoldDiagnostic,
    PBOResult,
    PerformanceDegradationResult,
    PromotionGateResult,
    PromotionTier,
    RegimeRobustnessResult,
    RobustnessComponentResult,
    RobustnessNeighborhoodResult,
    RobustnessScoreResult,
    StressScenario,
    StressTestResult,
    TemporalStabilityResult,
    ValidationCandidateResult,
    ValidationFoldMetric,
    ValidationRecord,
    ValidationRunResult,
)

__all__ = [
    "BootstrapResult",
    "CPCVResult",
    "CPCVSplit",
    "CandidateComparisonReport",
    "CandidateValidationProfile",
    "DeflatedSharpeResult",
    "MultipleTestingResult",
    "PBOFoldDiagnostic",
    "PBOResult",
    "ParameterSensitivityResult",
    "ParameterSensitivitySnapshot",
    "PerformanceDegradationResult",
    "PromotionGateResult",
    "PromotionTier",
    "RegimeRobustnessResult",
    "RobustnessComponentResult",
    "RobustnessNeighborhoodResult",
    "RobustnessScoreResult",
    "StressScenario",
    "StressTestResult",
    "TemporalStabilityResult",
    "ValidationBenchmarkResult",
    "ValidationBenchmarkRunner",
    "ValidationCandidateResult",
    "ValidationDataError",
    "ValidationEngine",
    "ValidationError",
    "ValidationFoldMetric",
    "ValidationPersistenceError",
    "ValidationRecord",
    "ValidationRunResult",
]
