export type OptionType="call"|"put";export type Side="buy"|"sell";export type QuoteQuality="strong"|"acceptable"|"weak"|"stale"|"incomplete"|"invalid";
export interface UnderlyingSnapshot{symbol:string;name:string;kind:"equity"|"etf"|"index";price:number;timestamp:string;freshness:"current"|"stale";source:string;warnings:string[]}
export interface ExpirationSummary{date:string;dte:number;classification:"weekly"|"monthly"|"quarterly"|"leaps";iv:number;liquidity:QuoteQuality;strikeCount:number;settlementStyle:"physical"|"cash";warnings:string[]}
export interface OptionContractRow{id:string;occSymbol:string;expiration:string;dte:number;strike:number;optionType:OptionType;bid:number|null;ask:number|null;last:number|null;bidSize:number;askSize:number;volume:number;openInterest:number;iv:number|null;delta:number|null;gamma:number|null;theta:number|null;vega:number|null;rho:number|null;intrinsic:number;extrinsic:number|null;moneyness:"itm"|"atm"|"otm";quoteTimestamp:string;quoteAgeSeconds:number;spread:number|null;liquidityScore:number;quality:QuoteQuality;exerciseStyle:"american"|"european";settlementStyle:"physical"|"cash";multiplier:number;adjusted:boolean;provider:string;certification:string}
export type LegRole="long_call"|"short_call"|"long_put"|"short_put"|"body"|"upper_wing"|"lower_wing"|"front_leg"|"back_leg"|"hedge"|"protective_leg"|"income_leg"|"custom";
export interface StrategyLeg{id:string;side:Side;optionType:OptionType;quantity:number;contract:OptionContractRow;role:LegRole;limitPrice:number|null;notes:string}
export interface StrategyTemplate{id:string;name:string;family:string;outlook:string;volatilityOutlook:string;risk:"defined"|"undefined";premium:"debit"|"credit"|"either";legCount:number;dteGuidance:string;limitations:string[]}
export interface PolicyRule{id:string;kind:"entry"|"exit"|"management"|"roll";name:string;enabled:boolean;parameters:Record<string,string|number|boolean>;priority:number}
export interface StrategyDraft{id:string;name:string;underlying:UnderlyingSnapshot;templateId:string;legs:StrategyLeg[];policies:PolicyRule[];notes:string;tags:string[];dirty:boolean;version:number}
export interface StrategyPreview{netMidpoint:number|null;cashFlow:"debit"|"credit"|"unknown";maxProfit:number|null;maxLoss:number|null;breakevens:number[];greeks:{delta:number;gamma:number;theta:number;vega:number;rho:number};warnings:string[];synthetic:boolean}
