export type VolMetricKind="observed"|"calculated"|"interpolated"|"model_derived"|"synthetic_fixture";export type NodeState="raw"|"interpolated"|"extrapolated"|"missing"|"failed";
export interface VolMetric{label:string;value:string;kind:VolMetricKind}
export interface SmileNode{id:string;expiration:string;dte:number;strike:number;moneyness:number;logMoneyness:number;delta:number;optionType:"call"|"put";bid:number;ask:number;midpoint:number;bidIv:number|null;askIv:number|null;midpointIv:number|null;providerIv:number|null;platformIv:number|null;volume:number;openInterest:number;quoteAge:string;liquidity:string;solver:string;converged:boolean;state:NodeState;quality:string;checksum:string}
export interface TermPoint{expiration:string;dte:number;atmIv:number;forwardAtmIv:number|null;realised:number;historical:number;eventPremium:number;quality:string;classification:string}
export interface ForwardPoint{near:string;far:string;nearVariance:number;farVariance:number;forwardVariance:number|null;forwardVolatility:number|null;status:"valid"|"invalid";diagnostic:string;checksum:string}
export interface HistoricalPoint{date:string;atmIv:number;realised:number;closeToClose:number;parkinson:number;garmanKlass:number;event:string|null}
export interface SurfaceNode{id:string;dte:number;strike:number;moneyness:number;delta:number;iv:number|null;totalVariance:number|null;state:NodeState;quality:number;source:string;checksum:string}
export interface SurfaceRecord{id:string;symbol:string;timestamp:string;provider:string;dataset:string;model:string;interpolation:string;expirations:number;nodes:number;coverage:number;quality:number;calibration:string;extrapolation:string;checksum:string;warnings:string[]}
export interface VolatilityFixture{metrics:VolMetric[];smile:SmileNode[];term:TermPoint[];forwards:ForwardPoint[];history:HistoricalPoint[];surfaceNodes:SurfaceNode[];surfaces:SurfaceRecord[]}
export interface SurfaceDraft{symbol:string;snapshot:string;ivSource:"platform"|"provider";expirations:string[];minimumNodes:number;model:"raw_nodes"|"interpolated_grid";interpolation:"log_moneyness"|"total_variance";extrapolation:"none"|"flat_wing";arbitrageChecks:boolean;acknowledged:boolean}
