"""Calendar and multi-expiry research analytics package."""

from .analytics import HistoricalAnalyticsEngine
from .api_contracts import (
    AnalyticsContractV1,
    AttributionContractV1,
    DiagnosticsContractV1,
    ReportContractV1,
    ResearchScoreContractV1,
    ValidationDashboardContractV1,
    WorkspaceContractV1,
)
from .benchmarks import CalendarResearchBenchmarkRunner, ResearchBenchmarkResult
from .calibration import CalibrationBucket, CalibrationDiagnostics, ScoreCalibrationEngine
from .engine import CalendarResearchEngine
from .exceptions import (
    CalibrationError,
    LifecyclePolicyError,
    ModelSimulationError,
    RefinementError,
    ResearchValidationError,
    SparseSampleWarningError,
)
from .expected_value import ExpectedValueComparison, ExpectedValueEngine, ExpectedValueResult
from .institutional import (
    AnalyticsSnapshot,
    AttributionEngine,
    PortfolioAnalyticsEngine,
    PortfolioDiagnosticsEngine,
    ResearchObservation,
    ResearchScore,
    ResearchScoreEngine,
    RobustnessEngine,
    RobustnessReport,
    StrategyComparisonEngine,
    audit_decision,
)
from .institutional_benchmarks import (
    InstitutionalResearchBenchmarkResult,
    InstitutionalResearchBenchmarkRunner,
)
from .lifecycle import (
    LifecycleEvaluationResult,
    LifecycleEvent,
    LifecyclePolicyConfig,
    LifecyclePolicyEngine,
)
from .models import (
    DEFAULT_DTE_BUCKETS,
    HistoricalAnalyticsResult,
    HistoricalRegimeFlag,
    HistoricalRegimeRecord,
    MultiExpiryStrategy,
    OpportunityComponent,
    OpportunityFeatures,
    OpportunityScoreResult,
    ParameterSweepCase,
    ParameterSweepGrid,
    RegimeClassificationInput,
    StrategyLeg,
    StrategyStatePoint,
    StrategyStateSeries,
    StrategyType,
)
from .probability import (
    HistoricalOutcomeRecord,
    HistoricalProbabilityEngine,
    HistoricalProbabilityReport,
    ModelPathOutcome,
    ModelProbabilityEngine,
    ModelProbabilityReport,
    ModelSimulationConfig,
    ProbabilityResult,
    ProbabilityType,
    to_model_outcomes_as_states,
)
from .ranking import (
    RankingCandidate,
    RankingComponent,
    RankingResult,
    RegimeConditionedRankingEngine,
)
from .refinement import DeterministicRefinementEngine, ScoredSweepCase
from .regime import HistoricalRegimeEngine
from .scoring import CalendarOpportunityScorer
from .strategies import StrategyFactory, normalize_dte_targets
from .sweep import ParameterSweepEngine

__all__ = [
    "AnalyticsContractV1",
    "AnalyticsSnapshot",
    "AttributionContractV1",
    "AttributionEngine",
    "CalendarOpportunityScorer",
    "CalendarResearchBenchmarkRunner",
    "CalendarResearchEngine",
    "CalibrationBucket",
    "CalibrationDiagnostics",
    "CalibrationError",
    "DEFAULT_DTE_BUCKETS",
    "DeterministicRefinementEngine",
    "DiagnosticsContractV1",
    "ExpectedValueComparison",
    "ExpectedValueEngine",
    "ExpectedValueResult",
    "HistoricalAnalyticsEngine",
    "HistoricalAnalyticsResult",
    "HistoricalOutcomeRecord",
    "HistoricalProbabilityEngine",
    "HistoricalProbabilityReport",
    "HistoricalRegimeEngine",
    "HistoricalRegimeFlag",
    "HistoricalRegimeRecord",
    "InstitutionalResearchBenchmarkResult",
    "InstitutionalResearchBenchmarkRunner",
    "LifecycleEvaluationResult",
    "LifecycleEvent",
    "LifecyclePolicyConfig",
    "LifecyclePolicyEngine",
    "LifecyclePolicyError",
    "ModelPathOutcome",
    "ModelProbabilityEngine",
    "ModelProbabilityReport",
    "ModelSimulationConfig",
    "ModelSimulationError",
    "MultiExpiryStrategy",
    "OpportunityComponent",
    "OpportunityFeatures",
    "OpportunityScoreResult",
    "ParameterSweepCase",
    "ParameterSweepEngine",
    "ParameterSweepGrid",
    "PortfolioAnalyticsEngine",
    "PortfolioDiagnosticsEngine",
    "ProbabilityResult",
    "ProbabilityType",
    "RankingCandidate",
    "RankingComponent",
    "RankingResult",
    "RegimeClassificationInput",
    "RegimeConditionedRankingEngine",
    "RefinementError",
    "ResearchBenchmarkResult",
    "ResearchObservation",
    "ResearchScore",
    "ResearchScoreContractV1",
    "ResearchScoreEngine",
    "ResearchValidationError",
    "ReportContractV1",
    "RobustnessEngine",
    "RobustnessReport",
    "ScoredSweepCase",
    "ScoreCalibrationEngine",
    "SparseSampleWarningError",
    "StrategyFactory",
    "StrategyLeg",
    "StrategyStatePoint",
    "StrategyStateSeries",
    "StrategyComparisonEngine",
    "StrategyType",
    "ValidationDashboardContractV1",
    "WorkspaceContractV1",
    "audit_decision",
    "to_model_outcomes_as_states",
    "normalize_dte_targets",
]
