"""Repository exports for database access patterns."""

from .backtesting import (
    BacktestCashLedgerRepository,
    BacktestEventRepository,
    BacktestLifecycleTriggerRepository,
    BacktestOrderIntentRepository,
    BacktestPortfolioSnapshotRepository,
    BacktestPositionLegRepository,
    BacktestPositionRepository,
    BacktestReproducibilityChecksumRepository,
    BacktestResearchFillRepository,
    BacktestRunComparisonRepository,
    BacktestRunRepository,
    BacktestScenarioResultRepository,
    BacktestValuationRepository,
)
from .market_data import (
    ContractsRepository,
    CorporateActionsRepository,
    DividendsRepository,
    EarningsRepository,
    InterestRatesRepository,
    ManifestsLineageRepository,
    QuotesRepository,
    UnderlyingPricesRepository,
)
from .optimization import OptimizationCandidateResultRepository, OptimizationRunRepository
from .portfolio import (
    PortfolioAllocationRepository,
    PortfolioClusterRepository,
    PortfolioConstraintRepository,
    PortfolioCorrelationRepository,
    PortfolioEligibleCandidateRepository,
    PortfolioRebalancePlanRepository,
    PortfolioRejectedCandidateRepository,
    PortfolioRiskContributionRepository,
    PortfolioRunRepository,
    PortfolioScenarioRepository,
)
from .reproducibility import (
    AuditRepository,
    CorporateActionNormalizationRepository,
    SnapshotRepository,
)
from .research import ResearchOpportunityRepository, ResearchRunRepository
from .validation import (
    ValidationCandidateResultRepository,
    ValidationFoldRepository,
    ValidationRunRepository,
)
from .volatility import VolatilityObservationRepository, VolatilitySliceRepository

__all__ = [
    "ContractsRepository",
    "BacktestCashLedgerRepository",
    "BacktestEventRepository",
    "BacktestLifecycleTriggerRepository",
    "BacktestOrderIntentRepository",
    "BacktestPortfolioSnapshotRepository",
    "BacktestPositionLegRepository",
    "BacktestPositionRepository",
    "BacktestReproducibilityChecksumRepository",
    "BacktestResearchFillRepository",
    "BacktestRunComparisonRepository",
    "BacktestRunRepository",
    "BacktestScenarioResultRepository",
    "BacktestValuationRepository",
    "CorporateActionsRepository",
    "DividendsRepository",
    "EarningsRepository",
    "InterestRatesRepository",
    "OptimizationCandidateResultRepository",
    "OptimizationRunRepository",
    "PortfolioAllocationRepository",
    "PortfolioClusterRepository",
    "PortfolioConstraintRepository",
    "PortfolioCorrelationRepository",
    "PortfolioEligibleCandidateRepository",
    "PortfolioRebalancePlanRepository",
    "PortfolioRejectedCandidateRepository",
    "PortfolioRiskContributionRepository",
    "PortfolioRunRepository",
    "PortfolioScenarioRepository",
    "ValidationCandidateResultRepository",
    "ValidationFoldRepository",
    "ValidationRunRepository",
    "ManifestsLineageRepository",
    "QuotesRepository",
    "UnderlyingPricesRepository",
    "AuditRepository",
    "CorporateActionNormalizationRepository",
    "ResearchOpportunityRepository",
    "ResearchRunRepository",
    "SnapshotRepository",
    "VolatilityObservationRepository",
    "VolatilitySliceRepository",
]
