import { Link, useParams } from "react-router-dom";
import { Badge, Button, Card, EmptyState, Metric } from "../components/ui";
import { DEMO_NOTICE, demoAlerts, demoJobs, demoProviders } from "../fixtures/demo";

const tone = (value: string) => value.includes("healthy") || value === "ready" || value === "current" ? "positive" : value.includes("critical") || value === "failed" || value === "stale" ? "negative" : "warning";

export function DemoBanner() { return <div className="demo-banner" role="status">{DEMO_NOTICE}</div>; }
export function HomePage() {
  return <><DemoBanner/><div className="metrics"><Metric label="Backend" value="Offline fixture mode" tone="warning"/><Metric label="Providers ready" value="2 / 6" tone="positive"/><Metric label="Active jobs" value="1"/><Metric label="Active alerts" value="1" tone="negative"/></div><div className="grid"><Card title="Provider readiness">{demoProviders.slice(0,4).map(p=><Link className="list-row" to={`/data/providers/${p.id}`} key={p.id}><strong>{p.displayName}</strong><Badge tone={tone(p.readiness)}>{p.readiness.replaceAll("_"," ")}</Badge></Link>)}</Card><Card title="Data freshness">{demoProviders.map(p=><div className="list-row" key={p.id}><span>{p.displayName}</span><Badge tone={tone(p.freshness)}>{p.freshness}</Badge></div>)}</Card><Card title="Recent research"><EmptyState title="No recent experiments" detail="Experiment workspaces arrive in Sprint 11C."/></Card><Card title="Portfolio risk"><EmptyState title="No portfolio selected" detail="Portfolio dashboards arrive in Sprint 11D."/></Card></div></>;
}
export function ProvidersPage() {
  return <><DemoBanner/><header className="page-heading"><div><h1>Data providers</h1><p>Configuration, readiness, health, and licensed-data boundaries.</p></div></header><div className="provider-grid">{demoProviders.map(p=><Link className="provider-card" to={`/data/providers/${p.id}`} key={p.id}><div><h2>{p.displayName}</h2><Badge tone={tone(p.health)}>{p.health.replaceAll("_"," ")}</Badge></div><dl><dt>Readiness</dt><dd>{p.readiness.replaceAll("_"," ")}</dd><dt>Freshness</dt><dd>{p.freshness}</dd><dt>Credentials</dt><dd>{p.credentialsConfigured ? "Configured" : "Missing"}</dd><dt>Certification</dt><dd>{p.certification}</dd></dl></Link>)}</div></>;
}
export function ProviderDetailPage() {
  const { providerId }=useParams(); const p=demoProviders.find(x=>x.id===providerId);
  if(!p)return <EmptyState title="Provider not found" detail="Return to the provider catalogue."/>;
  return <><DemoBanner/><div className="breadcrumbs"><Link to="/data/providers">Providers</Link> / {p.displayName}</div><header className="page-heading"><div><h1>{p.displayName}</h1><p>{p.limitations.join(" · ")||"Local provider"}</p></div><Badge tone={tone(p.readiness)}>{p.readiness.replaceAll("_"," ")}</Badge></header><nav className="tabs" aria-label="Provider detail sections">{["Overview","Capabilities","Catalogues","Jobs","Schedules","Health","Freshness","Certifications","Failures","Alerts","Configuration"].map(x=><button key={x}>{x}</button>)}</nav><div className="metrics"><Metric label="Health" value={p.health}/><Metric label="Freshness" value={p.freshness}/><Metric label="Credentials" value={p.credentialsConfigured?"Configured":"Missing"}/><Metric label="Certification" value={p.certification}/></div><Card title="Credential status"><p>Only presence and validation metadata are displayed. Secret values are never stored in the frontend.</p><Badge tone={p.credentialsConfigured?"positive":"warning"}>{p.credentialsConfigured?"Configured via environment":"Configuration required"}</Badge></Card></>;
}
export function JobsPage(){return <><DemoBanner/><h1>Provider jobs</h1><div className="table-wrap"><table><thead><tr><th>Job</th><th>Provider</th><th>Dataset</th><th>Status</th><th>Stage</th><th className="numeric">Processed</th><th className="numeric">Quarantined</th><th>Actions</th></tr></thead><tbody>{demoJobs.map(j=><tr key={j.id}><td><Link to={`/data/jobs/${j.id}`}>{j.id}</Link></td><td>{j.provider}</td><td>{j.dataset}</td><td><Badge tone={tone(j.status)}>{j.status}</Badge></td><td>{j.stage}</td><td className="numeric">{j.recordsProcessed.toLocaleString()}</td><td className="numeric">{j.quarantined.toLocaleString()}</td><td><Button>Inspect</Button></td></tr>)}</tbody></table></div></>}
export function JobDetailPage(){const {jobId}=useParams();const j=demoJobs.find(x=>x.id===jobId);if(!j)return <EmptyState title="Job not found" detail="The job may have expired."/>;return <><DemoBanner/><h1>{j.id}</h1><div className="metrics"><Metric label="Status" value={j.status}/><Metric label="Accepted" value={j.accepted.toLocaleString()}/><Metric label="Quarantined" value={j.quarantined.toLocaleString()}/><Metric label="Retries" value={j.retries}/></div><Card title="Immutable event timeline"><ol className="timeline"><li><time>{j.createdAt}</time><strong>planned</strong><p>Fixture job created.</p></li><li><time>{j.createdAt}</time><strong>{j.stage}</strong><p>{j.failureReason??"Processing synthetic fixture records."}</p></li></ol></Card><div className="actions"><Button>Export JSON</Button><Button>Export HTML</Button><Button>{j.status==="failed"?"Resume":"Cancel"}</Button></div></>}
export function AlertsPage(){return <><DemoBanner/><h1>Alert centre</h1>{demoAlerts.map(a=><Card key={a.id} title={a.message} action={<Badge tone="negative">{a.severity}</Badge>}><p>{a.provider} · {a.category} · occurred {a.occurrences} times</p><div className="actions"><Button>Acknowledge</Button><Button>Resolve</Button></div></Card>)}</>}
export function OperationalPage({kind}:{kind:string}){const descriptions:Record<string,string>={Schedules:"Create and inspect deterministic provider schedules.",Health:"Provider health metrics and supporting reasons.",Freshness:"Expected versus observed dataset coverage.",Gaps:"Missing sessions, symbols, chains, and remediation previews.",Storage:"Inventory, retention policies, and dry-run cleanup.",Readiness:"Configuration, credentials, samples, mappings, and blockers.",Samples:"Register licensed sample metadata without browser storage."};return <><DemoBanner/><h1>{kind}</h1><Card title={kind}><p>{descriptions[kind]}</p><EmptyState title={`No ${kind.toLowerCase()} records`} detail="Offline demo mode is active. Connect to the local backend to load persisted records."/></Card></>}
