"""Backtesting package exports for deterministic historical replay."""

from .analytics import (
    BacktestAnalyticsService,
    ComparisonResult,
    DrawdownPoint,
    GreeksAttribution,
    PerformanceAnalytics,
    PnLAttribution,
    PortfolioAnalyticsPoint,
    StrategyAnalyticsPoint,
)
from .api_contracts import (
    ApiEnvelopeV1,
    AttributionContractV1,
    ComparisonContractV1,
    CurveContractV1,
    HistoryContractV1,
    PortfolioConflictContractV1,
    ReplayControlContractV1,
    ReplaySnapshotContractV1,
    RunSummaryContractV1,
    StrategyCycleContractV1,
    TradeListContractV1,
)
from .arbitration import (
    ArbitrationDecision,
    ArbitrationPolicy,
    CompetingAction,
    CrossStrategyArbitrator,
)
from .benchmarks import BacktestBenchmarkResult, BacktestBenchmarkRunner
from .clock import HistoricalEventClock
from .engine import BacktestingEngine
from .event_taxonomy import (
    OverlayMetrics,
    RichEvent,
    RichEventPriority,
    RichEventType,
    default_priority,
)
from .exceptions import (
    BacktestingError,
    EventClockError,
    FillModelError,
    NoLookAheadError,
    StrategyLifecycleError,
    ValuationError,
)
from .execution import (
    ExecutionAction,
    ExecutionOrderType,
    ExecutionRequest,
    ExecutionSide,
    ExerciseAssignmentOrchestrator,
    FillAttempt,
    MultiLegExecutionCoordinator,
    MultiLegExecutionResult,
    OpenCloseEffect,
    execution_reproducibility_checksum,
)
from .execution_queries import ExecutionQueryService, QueryAsOfResult
from .fees import FeeItem, FeeModelRequest, ItemizedFeeModel
from .fill_models import FillModelRequest, FillModelResult, ResearchFillModelEngine
from .fills import BaselineResearchFillModel, FillModelConfig
from .guards import NoLookAheadGuard
from .models import (
    BacktestConfiguration,
    BacktestRunResult,
    BacktestStatus,
    ClockEvent,
    DeterministicEvent,
    EventClockConfig,
    EventType,
    FillPricePolicy,
    MarkPricePolicy,
    OrderAction,
    OrderIntent,
    OrderSide,
    PortfolioSnapshot,
    ScenarioTemplate,
    StrategyLifecycle,
    TradingSession,
)
from .orchestration import (
    CoordinatedEntryPlan,
    EntryMode,
    FillReconciliationEvent,
    IntegrityFailure,
    LegFillSnapshot,
    MultiLegOrchestrator,
    RollEligibilityResult,
    RollKind,
    RollPlan,
)
from .policies import (
    ConflictMode,
    ConflictResolutionResult,
    LifecyclePolicySignal,
    PolicyConflictResolver,
    PolicyDisposition,
)
from .queries import AsOfResult, BacktestAsOfQueryService
from .quote_selection import (
    QuotePriceSelection,
    QuoteSelectionPolicy,
    QuoteSelectionResult,
    QuoteSelector,
)
from .reconstruction import ReconstructedTrade, StrategyCycle, TradeReconstructionService
from .replay import BacktestReplayEngine, ReplayInspection, ReplaySnapshot, ReplayStatus
from .scenarios import DEFAULT_SCENARIO_LIBRARY
from .settlement import (
    AssignmentDecision,
    DividendSettlement,
    ExerciseDecision,
    ExpirationProcessingResult,
    PinRiskDiagnostic,
    SettlementEngine,
    SettlementPosting,
    SettlementResult,
)
from .state_machine import (
    ActionName,
    ActionPlan,
    GuardName,
    GuardResult,
    InvalidTransitionError,
    LifecycleState,
    StateTransitionRecord,
    StrategyStateMachine,
    TransitionTrigger,
)
from .strategies import (
    STRATEGY_TEMPLATE_NAMES,
    LegDirection,
    LegEffect,
    LegKind,
    LegSelectionCandidate,
    LegSelectionDiagnostic,
    LegSelectionEngine,
    LegSelectionPolicy,
    LegSelectionResult,
    MultiLegDefinitionLeg,
    MultiLegStrategyDefinition,
    SelectionPolicyType,
    StrategyDefinitionError,
    compile_template,
)
from .transition_guards import GuardEvaluationRequest, TransitionGuardLibrary
from .valuation import ValuationService

__all__ = [
    "ActionName",
    "ActionPlan",
    "ApiEnvelopeV1",
    "ArbitrationDecision",
    "AssignmentDecision",
    "ArbitrationPolicy",
    "AsOfResult",
    "AttributionContractV1",
    "BacktestAnalyticsService",
    "BacktestAsOfQueryService",
    "BacktestBenchmarkResult",
    "BacktestBenchmarkRunner",
    "BacktestConfiguration",
    "BacktestReplayEngine",
    "BacktestRunResult",
    "BacktestStatus",
    "BacktestingEngine",
    "BacktestingError",
    "BaselineResearchFillModel",
    "ClockEvent",
    "ComparisonContractV1",
    "ComparisonResult",
    "CompetingAction",
    "ConflictMode",
    "ConflictResolutionResult",
    "CoordinatedEntryPlan",
    "CrossStrategyArbitrator",
    "CurveContractV1",
    "DEFAULT_SCENARIO_LIBRARY",
    "DeterministicEvent",
    "default_priority",
    "DrawdownPoint",
    "DividendSettlement",
    "EntryMode",
    "EventClockConfig",
    "EventClockError",
    "EventType",
    "ExecutionAction",
    "ExecutionOrderType",
    "execution_reproducibility_checksum",
    "ExecutionQueryService",
    "ExecutionRequest",
    "ExecutionSide",
    "ExerciseAssignmentOrchestrator",
    "ExerciseDecision",
    "ExpirationProcessingResult",
    "FeeItem",
    "FeeModelRequest",
    "FillAttempt",
    "FillModelConfig",
    "FillModelError",
    "FillModelRequest",
    "FillModelResult",
    "FillPricePolicy",
    "FillReconciliationEvent",
    "GuardEvaluationRequest",
    "GuardName",
    "GuardResult",
    "GreeksAttribution",
    "HistoricalEventClock",
    "HistoryContractV1",
    "IntegrityFailure",
    "InvalidTransitionError",
    "LegDirection",
    "LegEffect",
    "LegFillSnapshot",
    "LegKind",
    "LegSelectionCandidate",
    "LegSelectionDiagnostic",
    "LegSelectionEngine",
    "LegSelectionPolicy",
    "LegSelectionResult",
    "LifecyclePolicySignal",
    "LifecycleState",
    "MarkPricePolicy",
    "ItemizedFeeModel",
    "MultiLegDefinitionLeg",
    "MultiLegExecutionCoordinator",
    "MultiLegExecutionResult",
    "MultiLegOrchestrator",
    "MultiLegStrategyDefinition",
    "NoLookAheadError",
    "NoLookAheadGuard",
    "OrderAction",
    "OpenCloseEffect",
    "OrderIntent",
    "OrderSide",
    "OverlayMetrics",
    "PerformanceAnalytics",
    "PnLAttribution",
    "PolicyConflictResolver",
    "PolicyDisposition",
    "PortfolioAnalyticsPoint",
    "PortfolioConflictContractV1",
    "PortfolioSnapshot",
    "PinRiskDiagnostic",
    "QueryAsOfResult",
    "QuotePriceSelection",
    "QuoteSelectionPolicy",
    "QuoteSelectionResult",
    "QuoteSelector",
    "ReconstructedTrade",
    "ReplayControlContractV1",
    "ReplayInspection",
    "ReplaySnapshot",
    "ReplaySnapshotContractV1",
    "ReplayStatus",
    "ResearchFillModelEngine",
    "RichEvent",
    "RichEventPriority",
    "RichEventType",
    "RollEligibilityResult",
    "RollKind",
    "RollPlan",
    "RunSummaryContractV1",
    "ScenarioTemplate",
    "SelectionPolicyType",
    "StateTransitionRecord",
    "STRATEGY_TEMPLATE_NAMES",
    "StrategyAnalyticsPoint",
    "StrategyCycle",
    "StrategyCycleContractV1",
    "StrategyDefinitionError",
    "StrategyLifecycle",
    "StrategyLifecycleError",
    "StrategyStateMachine",
    "SettlementEngine",
    "SettlementPosting",
    "SettlementResult",
    "TradeListContractV1",
    "TradeReconstructionService",
    "TradingSession",
    "TransitionGuardLibrary",
    "TransitionTrigger",
    "ValuationError",
    "ValuationService",
    "compile_template",
]
