"""Backtesting package exports for deterministic historical replay."""

from .benchmarks import BacktestBenchmarkResult, BacktestBenchmarkRunner
from .clock import HistoricalEventClock
from .engine import BacktestingEngine
from .exceptions import (
    BacktestingError,
    EventClockError,
    FillModelError,
    NoLookAheadError,
    StrategyLifecycleError,
    ValuationError,
)
from .fills import BaselineResearchFillModel, FillModelConfig
from .guards import NoLookAheadGuard
from .models import (
    BacktestConfiguration,
    BacktestRunResult,
    BacktestStatus,
    ClockEvent,
    DeterministicEvent,
    EventClockConfig,
    EventType,
    FillPricePolicy,
    MarkPricePolicy,
    OrderAction,
    OrderIntent,
    OrderSide,
    PortfolioSnapshot,
    ScenarioTemplate,
    StrategyLifecycle,
    TradingSession,
)
from .orchestration import (
    CoordinatedEntryPlan,
    EntryMode,
    FillReconciliationEvent,
    IntegrityFailure,
    LegFillSnapshot,
    MultiLegOrchestrator,
    RollEligibilityResult,
    RollKind,
    RollPlan,
)
from .policies import (
    ConflictMode,
    ConflictResolutionResult,
    LifecyclePolicySignal,
    PolicyConflictResolver,
    PolicyDisposition,
)
from .queries import AsOfResult, BacktestAsOfQueryService
from .scenarios import DEFAULT_SCENARIO_LIBRARY
from .state_machine import (
    ActionName,
    ActionPlan,
    GuardName,
    GuardResult,
    InvalidTransitionError,
    LifecycleState,
    StateTransitionRecord,
    StrategyStateMachine,
    TransitionTrigger,
)
from .strategies import (
    STRATEGY_TEMPLATE_NAMES,
    LegDirection,
    LegEffect,
    LegKind,
    LegSelectionCandidate,
    LegSelectionDiagnostic,
    LegSelectionEngine,
    LegSelectionPolicy,
    LegSelectionResult,
    MultiLegDefinitionLeg,
    MultiLegStrategyDefinition,
    SelectionPolicyType,
    StrategyDefinitionError,
    compile_template,
)
from .transition_guards import GuardEvaluationRequest, TransitionGuardLibrary
from .valuation import ValuationService

__all__ = [
    "AsOfResult",
    "BacktestAsOfQueryService",
    "BacktestBenchmarkResult",
    "BacktestBenchmarkRunner",
    "BacktestConfiguration",
    "BacktestRunResult",
    "BacktestStatus",
    "BacktestingEngine",
    "BacktestingError",
    "BaselineResearchFillModel",
    "ClockEvent",
    "DEFAULT_SCENARIO_LIBRARY",
    "DeterministicEvent",
    "EventClockConfig",
    "EventClockError",
    "EventType",
    "FillModelConfig",
    "FillModelError",
    "FillPricePolicy",
    "HistoricalEventClock",
    "MarkPricePolicy",
    "NoLookAheadError",
    "NoLookAheadGuard",
    "OrderAction",
    "OrderIntent",
    "OrderSide",
    "PortfolioSnapshot",
    "ScenarioTemplate",
    "SelectionPolicyType",
    "StrategyLifecycle",
    "StrategyDefinitionError",
    "STRATEGY_TEMPLATE_NAMES",
    "StrategyStateMachine",
    "StrategyLifecycleError",
    "TransitionTrigger",
    "TransitionGuardLibrary",
    "GuardEvaluationRequest",
    "GuardName",
    "GuardResult",
    "ActionName",
    "ActionPlan",
    "StateTransitionRecord",
    "InvalidTransitionError",
    "LifecycleState",
    "MultiLegOrchestrator",
    "EntryMode",
    "CoordinatedEntryPlan",
    "LegFillSnapshot",
    "FillReconciliationEvent",
    "RollKind",
    "RollPlan",
    "RollEligibilityResult",
    "IntegrityFailure",
    "PolicyConflictResolver",
    "ConflictMode",
    "PolicyDisposition",
    "LifecyclePolicySignal",
    "ConflictResolutionResult",
    "LegKind",
    "LegDirection",
    "LegEffect",
    "LegSelectionPolicy",
    "LegSelectionCandidate",
    "LegSelectionDiagnostic",
    "LegSelectionResult",
    "LegSelectionEngine",
    "MultiLegDefinitionLeg",
    "MultiLegStrategyDefinition",
    "compile_template",
    "TradingSession",
    "ValuationError",
    "ValuationService",
]
