"""Optimization engine foundation package."""

from .adapters import (
    ADAPTER_REGISTRY,
    BayesianOptimizationAdapter,
    GeneticOptimizationAdapter,
    OptimizerAdapter,
    OptimizerDependencyUnavailableError,
    SingleObjectiveSearchAdapter,
    TreeStructuredParzenEstimatorAdapter,
    get_optimizer_adapter,
    register_optimizer_adapter,
)
from .benchmarks import OptimizationBenchmarkResult, OptimizationBenchmarkRunner
from .checksums import (
    candidate_input_checksum,
    candidate_result_checksum,
    optimization_problem_checksum,
    reconcile_checksums,
)
from .constraints import ConstraintEngine
from .contracts import (
    DistributedExecutionContract,
    ExecutionDiagnostics,
    ExecutionMode,
    FoldResult,
    FoldSelectionReason,
    OptimizerAdapterContract,
    OptimizerCheckpoint,
    OptimizerDeterminism,
    OptimizerMode,
    OptimizerTrialRecord,
    ReproducibilityChecksumBundle,
    WalkForwardAggregationResult,
)
from .engine import OptimizationEngine
from .evaluation import CandidateEvaluationService
from .exceptions import (
    CandidateEvaluationError,
    CandidateGenerationError,
    ConstraintEvaluationError,
    OptimizationError,
    OptimizationValidationError,
    WalkForwardSplitError,
)
from .execution import (
    ExecutionResultBundle,
    ProcessPoolExecutionAdapter,
    SerialExecutionAdapter,
    SerializationError,
    ThreadPoolExecutionAdapter,
)
from .models import (
    BooleanParameter,
    Candidate,
    CandidateEvaluation,
    CandidateStatus,
    CategoricalParameter,
    ConditionalParameterRule,
    ConstraintDefinition,
    ConstraintResult,
    ConstraintSeverity,
    CustomValidationRule,
    DependentParameterRule,
    FloatRangeParameter,
    ForbiddenParameterCombination,
    IntegerRangeParameter,
    MissingMetricPolicy,
    NormalizationPolicy,
    ObjectiveDefinition,
    ObjectiveDirection,
    OptimizationProblem,
    OptimizationResult,
    OrderedDiscreteParameter,
    ParameterSpace,
    ParetoFrontResult,
    WalkForwardConfig,
    WalkForwardMode,
    WalkForwardSplit,
)
from .objectives import ObjectiveEngine
from .orchestration import WalkForwardOrchestrator
from .parameter_space import ParameterSpaceGenerator
from .pareto import ParetoEngine
from .presets import (
    CalibrationConstraintPreset,
    low_quality_data_penalty,
    maximum_brier_score,
    maximum_calibration_error,
    maximum_confidence_interval_width,
    minimum_lower_confidence_bound,
    minimum_out_of_sample_fold_count,
    minimum_regime_coverage,
    minimum_sample_size,
    overconfidence_penalty,
    sparse_regime_penalty,
    underconfidence_penalty,
)
from .selection import SelectionEngine, SelectionPolicy, SelectionPolicyType
from .walk_forward import WalkForwardEngine

__all__ = [
    "BooleanParameter",
    "Candidate",
    "CandidateEvaluation",
    "CandidateEvaluationError",
    "CandidateEvaluationService",
    "CandidateGenerationError",
    "CandidateStatus",
    "CategoricalParameter",
    "ConditionalParameterRule",
    "ConstraintDefinition",
    "ConstraintEngine",
    "ConstraintEvaluationError",
    "ConstraintResult",
    "ConstraintSeverity",
    "CustomValidationRule",
    "DependentParameterRule",
    "FloatRangeParameter",
    "ForbiddenParameterCombination",
    "IntegerRangeParameter",
    "MissingMetricPolicy",
    "NormalizationPolicy",
    "ObjectiveDefinition",
    "ObjectiveDirection",
    "ObjectiveEngine",
    "OptimizationBenchmarkResult",
    "OptimizationBenchmarkRunner",
    "OptimizationEngine",
    "OptimizationError",
    "OptimizationProblem",
    "OptimizationResult",
    "OptimizationValidationError",
    "OrderedDiscreteParameter",
    "ParameterSpace",
    "ParameterSpaceGenerator",
    "ParetoEngine",
    "ParetoFrontResult",
    "WalkForwardConfig",
    "WalkForwardEngine",
    "WalkForwardMode",
    "WalkForwardSplit",
    "WalkForwardSplitError",
    "ADAPTER_REGISTRY",
    "BayesianOptimizationAdapter",
    "candidate_input_checksum",
    "candidate_result_checksum",
    "CalibrationConstraintPreset",
    "DistributedExecutionContract",
    "ExecutionDiagnostics",
    "ExecutionMode",
    "ExecutionResultBundle",
    "FoldResult",
    "FoldSelectionReason",
    "GeneticOptimizationAdapter",
    "minimum_sample_size",
    "minimum_regime_coverage",
    "minimum_lower_confidence_bound",
    "maximum_brier_score",
    "maximum_calibration_error",
    "maximum_confidence_interval_width",
    "low_quality_data_penalty",
    "overconfidence_penalty",
    "sparse_regime_penalty",
    "underconfidence_penalty",
    "optimization_problem_checksum",
    "OptimizerAdapterContract",
    "OptimizerCheckpoint",
    "OptimizerDeterminism",
    "OptimizerMode",
    "OptimizerTrialRecord",
    "OptimizerAdapter",
    "OptimizerDependencyUnavailableError",
    "ProcessPoolExecutionAdapter",
    "ReproducibilityChecksumBundle",
    "reconcile_checksums",
    "SingleObjectiveSearchAdapter",
    "TreeStructuredParzenEstimatorAdapter",
    "get_optimizer_adapter",
    "register_optimizer_adapter",
    "SelectionEngine",
    "SelectionPolicy",
    "SelectionPolicyType",
    "SerializationError",
    "SerialExecutionAdapter",
    "SingleObjectiveSearchAdapter",
    "ThreadPoolExecutionAdapter",
    "WalkForwardAggregationResult",
    "WalkForwardOrchestrator",
    "minimum_out_of_sample_fold_count",
    "WalkForwardSplit",
    "WalkForwardSplitError",
]
